@startuml

entity User
entity User.email
entity User.password
entity User.confirmation
entity User.nickname
entity User.activationKey

 User.email -d-* User
 User.password -d-* User
 User.confirmation -d-* User
 User.nickname -d-* User
 User.activationKey -d-* User

entity Role
entity Role.name
entity Role.permissions

 Role.name -u-* Role
 Role.permissions -u-* Role
 
entity Review
entity Review.creationdate
entity Review.text
entity Review.topic
 Review.creationdate -u-* Review
 Review.text -d-* Review
 Review.topic -r-* Review

entity Action
entity Action.type
entity Action.actedAt

 Action.type --* Action
 Action.actedAt --* Action

entity Dataset
entity Datapoint
entity Datapoint.tableName
 Datapoint.tableName -u-* Datapoint
entity Entities
entity Entities.tableName
 Entities.tableName -r-* Entities
entity Conception
entity Metadata
entity Metadata.key
entity Metadata.value

 Metadata.key --* Metadata
 Metadata.value --* Metadata

 User "1,1" -l- "0,*" Review : Author
 User "0,*" -d- "1,1" Role
 User "1,1" -r- "0,*" Action
 Action "0,*" -d- "0,1" Dataset
 Action "0,*" -d- "0,1" Entities
 Action "0,*" -d- "0,1" Conception
 Action "0,*" -r- "0,1" Metadata
 Entities "1,1" -d- "0,*" Datapoint
 Datapoint "1,1" -r- "0,*" Conception
 Datapoint "0,*" -l- "1,1" Dataset
 Metadata "0,*" -- "1,1" Dataset
 Conception "0,*" -- "1,1" Dataset
@enduml
